# Generated by Django 5.2.5 on 2025-09-04 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_livro'),
    ]

    operations = [
        migrations.RenameField(
            model_name='autor',
            old_name='nome',
            new_name='autor',
        ),
        migrations.RenameField(
            model_name='autor',
            old_name='nascio',
            new_name='nacio',
        ),
        migrations.RenameField(
            model_name='autor',
            old_name='s_nome',
            new_name='s_autor',
        ),
    ]
